# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user  = Role.create(name: "user")
# admin = Role.create(name: "admin")

# [:admin, :user].each do |role|
#   Role.find_or_create_by_name({ name: role }, without_protection: true)
# end

Role.delete_all
User.delete_all
Category.delete_all
Tag.delete_all
Article.delete_all
Picture.delete_all

Role.create([{ name: 'admin' }, { name: 'user' }])

a1 = User.create({email: "admin@email.com", password: "11111111", password_confirmation: "11111111"})
a1.add_role :admin
u1 = User.create({email: "user1@email.com", password: "11111111", password_confirmation: "11111111"})
u2 = User.create({email: "user2@email.com", password: "11111111", password_confirmation: "11111111"})
u3 = User.create({email: "user3@email.com", password: "11111111", password_confirmation: "11111111"})

c1 = Category.create({name: "History"})
c2 = Category.create({name: "Economics"})
c3 = Category.create({name: "Culture"})

t1 = Tag.create({name: "tag1"})
t2 = Tag.create({name: "tag2"})
t3 = Tag.create({name: "tag3"})

a1 = Article.create({title: "Chambray meditation Tumblr", user_id: u2.id, category_id: c1.id, tags: [t1, t3], pictures: [Picture.create({image: File.new("#{Rails.root}/public/img/2.jpg")})], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a2 = Article.create({title: "Before they sold out Bushwick", user_id: u2.id, category_id: c2.id, tags: [t1], pictures: [Picture.create({image: File.new("#{Rails.root}/public/img/2.jpg")})], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a3 = Article.create({title: "Godard forage XOXO pop-up", user_id: u3.id, category_id: c3.id, tags: [t2], pictures: [Picture.create({image: File.new("#{Rails.root}/public/img/2.jpg")})], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a4 = Article.create({title: "Church-key organic readymade", user_id: u3.id, category_id: c1.id, tags: [t3], pictures: [Picture.create({image: File.new("#{Rails.root}/public/img/2.jpg")})], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a5 = Article.create({title: "Next level Odd Future whatever", user_id: u3.id, category_id: c2.id, tags: [t1, t2], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a6 = Article.create({title: "Pitchfork Brooklyn", user_id: u2.id, category_id: c1.id, tags: [t2], pictures: [Picture.create({image: File.new("#{Rails.root}/public/img/2.jpg")})], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})

a7 = Article.create({title: "Church-key organic readymade", user_id: u3.id, category_id: c2.id, tags: [t1, t2], content: "Thundercats seitan squid McSweeney's, mustache health goth typewriter. Chillwave small batch beard, blog plaid flexitarian sriracha health goth. Trust fund pug bitters listicle Austin, tofu messenger bag narwhal Godard. Artisan food truck plaid, seitan YOLO Tumblr typewriter. Fixie Carles sriracha selfies whatever Blue Bottle DIY, actually tousled vegan kogi quinoa wayfarers lumbersexual tofu. Organic synth Pitchfork ethical, mlkshk retro ugh +1 typewriter iPhone four loko messenger bag. Health goth Kickstarter twee, whatever brunch mixtape Pitchfork fixie PBR&B XOXO hashtag small batch authentic actually shabby chic.

Chambray meditation Tumblr Pitchfork Brooklyn, trust fund before they sold out photo booth McSweeney's cronut authentic taxidermy Thundercats. Shabby chic vinyl polaroid cliche, vegan squid Neutra messenger bag. Pour-over narwhal you probably haven't heard of them, salvia twee slow-carb retro keytar messenger bag drinking vinegar. Tofu blog forage viral. Master cleanse taxidermy mustache salvia, gentrify twee hashtag Portland Tumblr Echo Park 90's roof party. Single-origin coffee artisan Portland, American Apparel deep v lo-fi gluten-free Truffaut jean shorts roof party. Odd Future meggings cliche, four loko scenester Helvetica pickled mustache messenger bag meh DIY try-hard four dollar toast photo booth.

Church-key organic readymade, farm-to-table put a bird on it butcher Thundercats. Next level Odd Future whatever, distillery umami paleo artisan bicycle rights cornhole Intelligentsia DIY. Small batch lumbersexual photo booth Wes Anderson cold-pressed, drinking vinegar normcore taxidermy stumptown cronut tattooed squid Odd Future fanny pack Marfa. Yr chia +1 American Apparel flannel cold-pressed, kale chips direct trade freegan jean shorts tote bag. Before they sold out cardigan pug craft beer meh flannel, hashtag stumptown VHS PBR wayfarers cornhole migas selfies. Narwhal Blue Bottle banh mi YOLO, synth authentic organic. Selvage Tumblr crucifix keffiyeh.

Godard forage XOXO pop-up. Before they sold out Bushwick retro occupy Schlitz. Hashtag chambray asymmetrical, squid roof party next level slow-carb photo booth artisan. Art party kogi mlkshk trust fund Pinterest umami, jean shorts Brooklyn skateboard. Whatever meggings lo-fi street art. Scenester American Apparel kitsch Etsy chambray. Cold-pressed ethical 3 wolf moon pour-over."})
